export const azTranslations = {
  name: "Ad",
  surname: "Soyad",
  main: "Əsas",
  validThru: "Etibarlılıq",
  income: "Gəlir",
  expense: "Xərc",
  incomes: "Gəlirlər",
  expenses: "Xərclər",
  lastWeek: "son həftə",
  overview: "Ümumi baxış",
  outcomeCategories: "Xərc Kateqoriyaları",
  lastestTransactions: "Son Tranzaksiyalar",
  transactions: "Tranzaksiyalar",
  transactionId: "Tranzaksiya İD",
  earningCategories: "Gəlir Kateqoriyaları",
  transactionHistory: "Tranzaksiya Keçmişi",
  transfer: "Transfer",
  from: "dan",
  balance: "Balans",
  myBalance: "Balansım",
  accountOwner: "Hesab Sahibi",
  title: "Başlıq",
  card: "Kart",
  cards: "Kartlar",
  cardHolder: "Kart Sahibi",
  cardName: "Kart adı",
  cardInformation: "Kart İnformasiyası",
  cardNumber: "Kart Nömrəsi",
  newCard: "Yeni kart",
  cardList: "Kart Siyahısı",
  amount: "Məbləğ",
  category: "Kateqoriya",
  categories: "Kateqoriyalar",
  categoryName: "Kateqoriya adı",
  noCategory: "Kateqoriyasız",
  newCategory: "Yeni kateqoriya",
  categoryColor: "Kateqoriya rəngi",
  send: "Göndər",
  completed: "Tamamlandı",
  pending: "Gözlənilir",
  declined: "İmtina edildi",
  targetMoney: "Hədəf məbləğ",
  create: "Yarat",
  note: "Əlavə qeyd",
  duration: "Müddət",
  year: "il",
  completeOrder: "Sifarişi tamamla",
  limit: "Limit",
  bankName: "Bank adı",
  disable: "Deaktiv et",
  active: "Aktiv et",
  showPendings: "Gözləyənləri Göstər",
  recieverSender: "Alıcı/Göndərən",
  status: "Status",
  accept: "Qəbul et",
  decline: "Imtina et",
  password: "Şifrə",
  newPassword: "Yeni şifrə",
  reNewPassword: "Yeni şifrənin təkrarı",
  save: "Saxla",
  delete: "Sil",
  monday: "B.e",
  tuesday: "Ç.a",
  wednesday: "Ç",
  thursday: "C.a",
  friday: "C",
  saturday: "Şən",
  sunday: "Baz",
  uploadBtnText: "Yükləmək üçün klikləyin və ya sürüşdürüb buraxın",
  or: "və ya",
  max: "MAKS.",
  settings: "Parametrlər",
  dismiss: "Gizlət",
  welcome: "Xoş gəldiniz",
  signIn: "Sign In",
  email: "Email Address",
  password: "Password",
  continue: "Continue",
  dontHaveAccount: "Don't have an account?",
  forgotPass: "Forgot Password?",
};
