export const enTranslations = {
  name: "Name",
  surname: "Surname",
  main: "Main",
  validThru: "Valid Thru",
  income: "Income",
  expense: "Expense",
  lastWeek: "last week",
  overview: "Overview",
  outcomeCategories: "Outcome Categories",
  lastestTransactions: "Lastest Transactions",
  transactionId: "Transaction ID",
  transactions: "Transactions",
  transactionHistory: "Transaction History",
  earningCategories: "Earning Categories",
  expenses: "Expenses",
  incomes: "Incomes",
  transfer: "Transfer",
  from: "from",
  balance: "Balance",
  myBalance: "My Balance",
  accountOwner: "Account Owner",
  title: "Title",
  card: "Card",
  cardHolder: "Card Holder",
  cards: "Cards",
  cardName: "Card name",
  newCard: "New card",
  cardList: "Card List",
  cardInformation: "Card Information",
  cardNumber: "Card Number",
  amount: "Amount",
  category: "Category",
  categories: "Categories",
  categoryName: "Category name",
  noCategory: "No Category",
  newCategory: "New category",
  categoryColor: "Category color",
  send: "Send",
  completed: "Completed",
  pending: "Pending",
  declined: "Declined",
  targetMoney: "Target money",
  create: "Create",
  note: "Note",
  duration: "Duration",
  year: "year",
  completeOrder: "Complete order",
  limit: "Limit",
  bankName: "Bank name",
  disable: "Disable",
  active: "Active",
  showPendings: "Show Pendings",
  recieverSender: "Reciever/Sender",
  status: "Status",
  accept: "Accept",
  decline: "Decline",
  password: "Password",
  newPassword: "New password",
  reNewPassword: "Re-new password",
  shortDayNames: ["Mon.", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  monday: "Mon",
  tuesday: "Tue",
  wednesday: "Wed",
  Thursday: "Thu",
  friday: "Fri",
  saturday: "Sat",
  sunday: "Sun",
  uploadBtnText: "Click to upload or drag and drop",
  or: "or",
  max: "MAX.",
  save: "Save",
  delete: "Delete",
  settings: "Settings",
};
